### ISSUE TITLE
testHasGoogleMockTests fires when running the tests.

### ISSUE THREAD

**Issue by ftrofin** [macmade/gmock-xcode#2]
First off, thanks for creating this XCTest bridge project! It is very useful.

I must be doing something wrong, I followed the instructions in the  README and everything compiles and links fine. However, when I run my test from Xcode (from Test Navigator) I get this assert firing in GMXCTestBridge.mm:
- ( void )testHasGoogleMockTests
  {
  XCTAssertTrue( __inited, "No GMock test" );
  }

Could not find anything on the Internet related to this. Seems that my tests are not registering? Can you please update the instructions so this doesn't happen anymore?

Thanks!

Florin

**Comment by macmade** [comment]
Thanks for the report. : )

Well, this usually means that no tests are available in the test bundle (or that the gmock-xcode bridge has failed to detect them for some reason).

How did you define them? Is your project public so I can take a look?

**Comment by ftrofin** [comment]
Thanks for looking at this. After fiddling with the schemes and targets (and dependencies) I got past that. Not sure what the problem was. Unfortunately the project is not public. If I run into the issue again I'll come back with more diagnostic information.
