### ISSUE TITLE
Seeing following error

### ISSUE THREAD

**Issue by ShashankBabu** [macmade/gmock-xcode#3]
Hello I tried to link  gmock , gtest and GoogleMock from gmock-xcode repo to write some Mock test cases. I was able to link all three at runtime to my test target However it complains with following error message "ld: framework not found XCTest" . I tried linking it from following path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.Platform/Developer/Library/Frameworks/XCTest.framework but it still complains with same error message. Is this a known issue

**Comment by macmade** [comment]
This is not a known issue.

How are you creating your unit tests?

You should have a Unit Test Bundle in your target list. In the build settings, ensure that **Framework Search Paths** is set to `$(DEVELOPER_FRAMEWORKS_DIR)`, and that **Header Search Paths** is set accordingly.

Then link your Unit Test Bundle with the `GoogleMock.framework`. That's all...

**Comment by macmade** [comment]
Closing as no feedback and as this doesn't look like a real issue.
Feel free to reopen...
