### ISSUE TITLE
How to include test files from other directory?

### ISSUE THREAD

**Issue by bipulr** [macmade/gmock-xcode#4]
This is not specifically any issue, rather clarification needed to use it. My requirement is that I want to keep all test.cpp files in some other directory outside gmock-xcode, not in GoogleMockTests directory. If I add a directory in GoogleMockTests from xcode UI, it does not run the tests in the directory using xcode ui to run the tests.

**Comment by bipulr** [comment]
Closing it, as I got the clarity.

**Comment by macmade** [comment]
Sorry for the late answer...
You can obviously place your tests wherever you want... Different target, project, etc.

Glad you resolved this.
