### ISSUE TITLE
testHasGoogleMockTests always failing.

### ISSUE THREAD

**Issue by bipulr** [macmade/gmock-xcode#5]
I created a new test target from test navigator and selected language as objective-C as that is the only option available. I am using XCode 6. I added GoogleMock, gtest and gmock to "Target Dependencies" and "Link Binary With Libraries" in "Build Phases" setting. I add a .cpp file which contains the sample test code as written in README of gmock-xcode. I added that .cpp file in "Compile Sources" as well in "Build Phases" settings.

But when I run the test target from test navigator, it compiles and links properly, but testHasGoogleMockTests always fails as it is not able to detect the sample tests added in .cpp file.

What I am missing?

**Comment by bipulr** [comment]
@macmade Can you please help me out with this issue.

**Comment by bipulr** [comment]
I could resolve this by adding only GoogleMock.Framework to "Link Binary With Libraries" in "Build Phase" setting. Earlier I had added gtest and gmock as well, as it is written in README of gmock-xcode. I am not sure what's happening here. Atleast the documentation should be corrected.

**Comment by macmade** [comment]
Yes, you only have to link with GoogleMock.Framework. The other frameworks are linked automatically.

I'll correct to documentation accordingly. Thanks for the report.
