### ISSUE TITLE
How far behind the googletest repo is this project?

### ISSUE THREAD

**Issue by kdawgwilk** [macmade/gmock-xcode#6]
Would be possible to include the google test repo into this as a submodule that can be updated fairly easily?

**Comment by macmade** [comment]
Yes, it would indeed be something nice!

Actually, I'm using gmock 1.7.0, which was released in september 2013.
Seems like a dinosaur, but the latest version, released in august 2016, is "only" 1.8.0.

So I'll just try with that new version, and see if everything is still compatible...
I'll leave this issue open in the meantime.

Thanks for the suggestion : )

**Comment by macmade** [comment]
All right, latest version now includes the latest googletest release, aka 1.8.0.

Binaries are still included, as this is more convenient.  
But the supplied makefile automatically downloads googletest from GitHub, so it's now very easy to update (just change the version number in the makefile).

**Comment by macmade** [comment]
Tell me if I can close the issue : )

**Comment by kdawgwilk** [comment]
Thanks for this! 👍
